project:
  type: website

website:
  title: "Robin's Quanty Ramblings"
  navbar:
    right:
      - icon: github
        href: https://github.com/P0BS
      - icon: bluesky
        href: https://bsky.app/profile/p0bs.bsky.social
format:
  html:
    theme: [morph, theming.scss]
    css: styles.css

editor: visual