project:
  type: website

website:
  title: "Rob's Quanty Ramblings"
  navbar:
    right:
      - icon: github
        href: https://github.com/P0BS
      - icon: bluesky
        href: https://bsky.app/profile/p0bs.bsky.social
format:
  html:
    theme:
      light:
        - cosmo
        - brand
      dark:
        - slate
        - brand
editor: visual