project:
  type: website

website:
  title: "Rob's Quanty Ramblings"
  navbar:
    right:
      - icon: github
        href: https://github.com/P0BS
      - icon: bluesky
        href: https://bsky.app/profile/p0bs.bsky.social
format:
  html:
    include-after-body: _include-after-body.html
    theme:
      light:
        - cosmo
        - brand
      dark:
        - slate
        - brand
editor: visual
listing:
  contents:
    - posts
    - path: https://github.com/p0bs/PL-scan?tab=readme-ov-file#predicting-this-seasons-premier-league
      title: "Today's preditions for the 2025/26 Premier League"
      date: "2025-10-27"
      categories: [sport]
      image: "posts/prempredict/PPlogo.png"
      description: "Updated daily, here are my estimates for each team's chances of winning the league, getting into Europe and getting relegated."
  sort: "date desc"
  type: default
  